### PR TITLE
Landing page more in line with new designs

### PR DESCRIPTION
**Pull request by cmc333333**
Please ignore the missing images:

screen shot 2014-10-22 at 5 37 40 pm
screen shot 2014-10-22 at 5 37 52 pm
screen shot 2014-10-22 at 5 38 04 pm

### CODE REVIEW

**Comment by khandelwal** [comment]
This is all front-end related code. Can anyone else review?

**Comment by seanherron** [comment]
LGTM, but I think @cmc333333 is going to replace CSS `ID`s with `class` so will wait on that change before merging.

**Comment by cmc333333** [comment]
ids -> classes

**Comment by seanherron** [comment]
:+1:

**Pull request merged**
