### PR TITLE
A start on a vagrant dev environment.

### PR DESCRIPTION
**Pull request by phildini**
Right now everything works, but could be set up to be more
user friendly through the use of automatic aliases, etc.

Also, a "dev" settings set that can be used out of the box but allows
debug.

### CODE REVIEW

**Comment by phildini** [comment]
This is also a starting point on #352

**Comment by seanherron** [comment]
Thanks so much, @phildini! I actually expanded on your suggestions and rewrote the entire `README` as well as customized the Vagrantfile and provisioning script to include some fixtures and data specific to this repository (we merged that literally 3 minutes before you opened this PR, see https://github.com/18F/peacecorps-site/pull/356). I don't think there are any enhancements you did here that aren't present in that PR, can you take a look & try things out to see if this helps?

**Comment by phildini** [comment]
I'll go look right now. Thanks for jumping on it!

**Comment by seanherron** [comment]
One quick note - you may want to pull from https://github.com/18F/peacecorps-site/pull/358 instead, as I removed a nodejs dependency that was messing things up.

**Comment by phildini** [comment]
Hah! I just ran into that.

PJJ
http://philipjohnjames.com

**Pull request closed without merging**
