### PR TITLE
Paygov Callback Request Test (Staging Only)

### PR DESCRIPTION
**Pull request by sshami**
@defbyte Let me know if anything needs to be modified.

### CODE REVIEW

**Comment by defbyte** [comment]
Shoot, Circle CI tests have failed due to an issue installing requirements @sshami

**Comment by sshami** [comment]
@defbyte Damn. Let me try sending the PR again.

**Comment by defbyte** [comment]
@sshami in your local development environment can you please run `pip freeze` and upload the output? We have dependencies that are not pinned to a version number, and I am concerned there have been updates to packages that might be triggering this issue, and one that I am facing locally.

**Comment by sshami** [comment]
@defbyte Sure thing. Versions currently on my working local dev:

Django==1.7.11
DjangoRestless==0.0.10
Jinja2==2.8
Markdown==2.6.4
MarkupSafe==0.23
Pillow==3.0.0
PyYAML==3.11
backports-abc==0.4
boto==2.38.0
click==5.1
decorator==4.0.4
defusedxml==0.4.1
django-admin-sortable2==0.3.3
django-appconf==1.0.1
django-debug-toolbar==1.4
django-elasticache==0.0.3
-e git+https://github.com/18f/django-gzipping-cache.git@25d2b0a7c0524fd4fa92bfecbf132e30a8ff64e3#egg=django_gzipping_cache-origin/master
django-jinja==1.0.4
django-localflavor==1.1
django-overextends==0.4.0
django-sirtrevor==0.2.4
-e git+https://github.com/coagulant/django-storages-py3.git@73920742505b0c86b2fbc30274ff8b111e9b6f48#egg=django_storages-py3
django-tinymce==2.0.6
djangorestframework==3.3.3
flake8==2.5.0
ipython==4.0.0
ipython-genutils==0.1.0
livereload==2.4.0
markdown2==2.3.0
mccabe==0.3.1
mkdocs==0.14.0
path.py==8.1.2
pep8==1.5.7
pexpect==4.0.1
pickleshare==0.5
psycopg2==2.5.3
ptyprocess==0.5
pyflakes==1.0.0
pylibmc==1.5.0
python-gnupg==0.3.8
python-logstash==0.4.5
pytz==2015.7
simplegeneric==0.8.1
six==1.10.0
sphinx-me==0.3
sqlparse==0.1.18
tornado==4.3
traitlets==4.0.0

**Comment by defbyte** [comment]
thanks, I am thinking based on the Circle CI, that we need to pin `Pillow==3.0.0` am running a test locally now @sshami

**Pull request closed without merging**
