### PR TITLE
Make memorial images in line with mockups

### PR DESCRIPTION
**Pull request by seanherron**
This PR changes the styling of the memorial page to be more in line with the mockups. I'm using a few inline styles I want to optimize, but didn't want to substantially edit the SCSS as @msecret has a structure set up that I didn't want to interfere with.

screen shot 2015-01-30 at 6 56 21 pm

### CODE REVIEW

**Comment by msecret** [comment]
Wouldn't this mean that the actual fund text won't be shown? I think Eric's mocks required a text section to come up when you click on a fund.

**Comment by ericronne** [comment]
Don't forget the 3-pixel stroke around the circles
#AAA698

Also add space above the circles (which are larger than the design, but that's okay because i believe the client wanted to give these funds a little more prominence on the page)...
special funds - adj

**Comment by cmc333333** [comment]
Something to keep in mind, here: there are now 9 memorial funds.

**Comment by cmc333333** [comment]
Closing as this is quite stale.

**Pull request closed without merging**
