### PR TITLE
Removed Header Beta Language

### PR DESCRIPTION
**Pull request by sshami**
Removed the beta language from the header.

### CODE REVIEW

**Comment by sshami** [comment]
@cmc333333 When you get the chance, could you merge and deploy this? Thanks

**Comment by cmc333333** [comment]
This is on staging now; I'll deploy to prod at some point over the weekend. Looks good!

**Comment by sshami** [comment]
@cmc333333 Thanks!

**Comment by cmc333333** [comment]
And, live.

**Comment by sshami** [comment]
@cmc333333 Thanks

**Pull request merged**
