### PR TITLE
Remove 18F references.

### PR DESCRIPTION
**Pull request by defbyte**
I'd love to get an eye on this from @sshami and @jacobgodin if you don't mind. Most of these edits are URIs to the GitHub repository.

There are a couple that referenced a service 18F setup called Fugacio.us for secure transmission of sensitive data. We could start stone-age with password delivery by phone, and then step it up with a service that meets security requirements.

Also, I opened an Issue #381 for CircleCI integration.

### CODE REVIEW

**Comment by jacobgodin** [comment]
Looks good after a once-over. Haven't gone through the repo to see if there are any more we should replace, but I assume you've done a scan

**Comment by sshami** [comment]
All looks good! Thanks.

**Comment by defbyte** [comment]
Well, that was easy! I setup CircleCI for this project #381

**Comment by sshami** [comment]
Can merge this to master and I'll work on rebasing pull request #377 . thanks!

**Pull request merged**
