### PR TITLE
Include IE8 warning

### PR DESCRIPTION
**Pull request by cmc333333**
Looks like:

screen shot 2015-02-26 at 10 41 33 am

Also fixed an incorrect closing tag.

### CODE REVIEW

**Comment by seanherron** [comment]
Maybe include this at the end of it? `<a href="http://browsehappy.com">Learn how to update your browser</a>.`

**Comment by cmc333333** [comment]
Smart

**Comment by seanherron** [comment]
also `target=_blank`

**Comment by cmc333333** [comment]
Updated:
screen shot 2015-02-26 at 10 54 23 am

**Pull request merged**
