### PR TITLE
Memo and custom field generation

### PR DESCRIPTION
**Pull request by cmc333333**
Match the fields that are generated in the current donations page.

### CODE REVIEW

**Comment by khandelwal** [comment]
Can you explain how and when we would use generate_custom_fields? If everything was hooked up, how is this used?

**Comment by cmc333333** [comment]
Neither the memo nor the custom fields (nor the billing info, etc.) are processed by pay.gov when the browser is sent over. Pay.gov only accepts the agency id, tracking id, and app name from the browser.

It uses that to make a request to our server, at which point we provide the memo, custom fields, billing into, etc. So both the agency memo and the custom fields will need to operate on the stored model. In the meantime, just use the form's data.

**Comment by cmc333333** [comment]
Alternatively, the model could have fields for memo/custom rather than storing the state of the form. We could go so far as to have the form generate the XML we need to respond with and have the model only store (tracking id, XML blob) pairs.

This would certainly make encryption easier.

**Comment by khandelwal** [comment]
I think we need to talk more about this. However, that doesn't change the fact that this PR is good to go.

**Pull request merged**
